export const courses = [
  { 
    id:1,
    title: "Yoga Teacher Training",
    duration: "4 Months",
    image: "/img/training1.jpg",
    rating: 4.8,
    reviews: 124,
    category: "Yoga",
    // instructor: "Priya Sharma",
    // instructorBio:
    //   "Certified Yoga Alliance instructor with 12 years of teaching experience, specializing in Hatha and Vinyasa yoga.",
    // instructorAvatar: "https://randomuser.me/api/portraits/women/44.jpg",
    color: "#6366F1",
    students: 85,
    level: "Intermediate",
    description:
      "This comprehensive 200-hour certification program covers all aspects of professional yoga teaching. You'll learn yoga philosophy, anatomy, and teaching methodology through both theory and practice. The course includes hands-on training in asana techniques, alignment, and sequencing. Graduates will be qualified to teach yoga internationally with a recognized certification.", 
      descriptions:"This 200-hour course provides internationally recognized certification to teach yoga professionally. It includes classical Hatha Yoga, Vinyasa Flow, teaching methodology, functional anatomy, yogic lifestyle, mantra chanting, and kriyas (cleansing techniques). Trainees undergo immersive practice sessions, peer teaching, and receive feedback from experienced mentors. Additionally, the course covers yoga for special populations (seniors, pregnant women, children), and how to design safe and effective yoga classes. By the end, participants are fully prepared to lead yoga sessions in studios, schools, retreats, and corporate settings.",
    syllabus: [
      "Yoga Philosophy & History",
      "Anatomy & Physiology", 
      "Ashtanga Vinyasa Flow",
      "Hatha Yoga",
      "Shatkarma(Cleansing)",
      "Pranayama",
      "Mudra and Bandha",
      "Meditation",
    ],
    certification: "Yoga Alliance RYT 200",
    prerequisites: "Minimum Qualification Madhyamik",
    learningOutcomes: [
      "Ability to design and lead yoga classes",
      "Understanding of yoga anatomy and injury prevention",
      "Skills to modify poses for different body types",
      "Knowledge of sequencing principles",
    ],
    // startDates: ["2023-09-15", "2024-01-10", "2024-04-05"],
    // price: "₹45,000",
    // discountPrice: "₹38,000 (early bird)",
  },
  { 
    id:2,
    title: "Massage Therapy Certification",
    duration: "3 Months",
    image: "/img/massage.jpg",
    rating: 4.5,
    reviews: 89,
    category: "Therapy",
    // instructor: "Arjun Patel",
    // instructorBio:
    //   "Licensed massage therapist with 8 years of clinical experience, trained in Swedish, Deep Tissue, and Sports massage techniques.",
    // instructorAvatar: "https://randomuser.me/api/portraits/men/32.jpg",
    color: "#10B981",
    students: 62,
    level: "Beginner",
    description:
      "This hands-on training program teaches various massage modalities for professional practice. Students learn Swedish, Deep Tissue, and therapeutic massage techniques through practical sessions. The curriculum covers anatomy, client assessment, and professional ethics in massage therapy. Graduates will be prepared to work in spas, clinics, and wellness centers with NCBTMB-approved certification.", 
      descriptions:"This hands-on training program equips students with diverse therapeutic bodywork techniques to support physical healing and relaxation. The course includes modules on anatomy, physiology, pressure point therapy, trigger point release, lymphatic drainage, hot stone massage, and traditional Indian massage styles like Abhyanga and Marma therapy. Emphasis is placed on client assessment, safety protocols, and ethical practices. Internships and real-world practice help build confidence and professionalism. Upon completion, students can work in wellness resorts, physiotherapy clinics, and rehabilitation centers, or start their own massage practice.",
    syllabus: [
      "Yoga Philosophy",
      "Therapeutic Yoga",
      "Therapeutic Exercise",
      "Anatomy & Physiology",
      "Diseases"
      
    ],
    certification:
      "National Certification Board for Therapeutic Massage & Bodywork (NCBTMB) approved",
    prerequisites: "Minimum Qualification Madhyamik",
    learningOutcomes: [
      "Proficiency in multiple massage techniques",
      "Understanding of contraindications",
      "Professional client communication skills",
      "Knowledge of hygiene and sanitation standards",
    ],
    // startDates: ["2023-10-01", "2024-02-05", "2024-06-10"],
    // price: "₹32,000",
    // discountPrice: "₹28,000 (if paid in full)",
  },
  {   
    id:3,
    title: "Professional Physiotherapy",
    duration: "6 Months",
    image: "/img/physio.jpg",
    rating: 4.7,
    reviews: 156,
    category: "Medical",
    // instructor: "Dr. Neha Gupta",
    // instructorBio:
    //   "Doctor of Physical Therapy with 15 years of clinical experience specializing in orthopedic and sports rehabilitation.",
    // instructorAvatar: "https://randomuser.me/api/portraits/women/68.jpg",
    color: "#3B82F6",
    students: 112,
    level: "Advanced",
    description:
      "This advanced training enhances physiotherapy skills with evidence-based practice for healthcare professionals. Participants learn musculoskeletal assessment, therapeutic exercises, and manual therapy techniques. The program includes clinical case studies and neurological rehabilitation modules. CEUs are available for licensed professionals to maintain their credentials.", 
      descriptions:"A career-focused training designed for individuals aiming to specialize in restoring physical function and mobility. The program offers in-depth instruction in orthopedic physiotherapy, neurological rehabilitation, sports therapy, post-surgical care, pediatric physiotherapy, and cardio-pulmonary therapy. Emphasis is placed on diagnostic tools, physical assessment, therapeutic exercises, and assistive technology. Clinical rotations and real-case applications prepare students to work in hospitals, fitness centers, sports academies, or as independent practitioners. Soft skills like patient communication, documentation, and counseling are also integrated.",
    syllabus: [
      "Anatomy-Physiology",
      "Exercises Therapy",
      "Diseases Related Physiotherapy",
      "Electro Therapy",
      
    ],
    certification:
      "Continuing Education Units (CEUs) available for licensed professionals",
    prerequisites: "Minimum Qualification 10+2 Passed / Appeared",
    learningOutcomes: [
      "Advanced assessment skills",
      "Ability to design comprehensive treatment plans",
      "Proficiency in manual therapy techniques",
      "Understanding of current research in physiotherapy",
    ],
    // startDates: ["2023-11-01", "2024-03-15"],
    // price: "₹68,000",
    // discountPrice: "₹60,000 (for early registration)",
  },
  {   
    id:4,
    title: "Diploma in Yoga Therapy",
    duration: "2 Years",
    image: "/img/yogas.jpg",
    rating: 4.9,
    reviews: 210,
    category: "Yoga",
    // instructor: "Ravi Mishra",
    // instructorBio:
    //   "Yoga therapist with 20 years of experience integrating traditional yoga with modern medical knowledge.",
    // instructorAvatar: "https://randomuser.me/api/portraits/men/75.jpg",
    color: "#F59E0B",
    students: 94,
    level: "Professional",
    description:
      "This in-depth program combines yoga philosophy with therapeutic applications for health conditions. Students learn to develop yoga interventions for various pathologies and psychological conditions. The curriculum includes clinical practicum and case study development under expert guidance. Graduates receive IAYT accreditation to practice as professional yoga therapists.", 
      descriptions:"This advanced diploma program offers a scientific and holistic approach to health using yoga as a therapeutic tool. It blends ancient yogic practices with contemporary medical understanding to support the prevention and management of chronic illnesses such as asthma, arthritis, diabetes, depression, and spinal disorders. The curriculum includes detailed modules on anatomy, physiology, yoga psychology, diet and nutrition, and Ayurveda. Students gain practical experience through clinical case studies, yoga therapy consultations, and internships. Graduates are equipped to work in rehabilitation centers, hospitals, wellness clinics, or as private yoga therapists.",
    syllabus: [
      "Asana",
      "Exercise",
      "Pranayam",
      "Anatomy & Physiology",
      "Nutrition",
      "Practice Of Yoga Medicine",
      "Yoga Philosophy"
    ],
    certification:
      "International Association of Yoga Therapists (IAYT) accredited",
    prerequisites: "Minimum Qualification Graduation Appeared / He or She has to undertake any other Course except Diploma to qualify for the above Course",
    learningOutcomes: [
      "Ability to design therapeutic yoga programs",
      "Understanding of contraindications for various conditions",
      "Skills to work with special populations",
      "Knowledge to collaborate with healthcare providers",
    ],
    // startDates: ["2024-01-15"],
    // price: "₹1,20,000",
    // paymentOptions: "Installment plans available",
  },
  {   
    id:5,
    title: "Judicial Training Program",
    duration: "3 Months",
    image: "/img/judges.jpg",
    rating: 4.3,
    reviews: 67,
    category: "Professional",
    // instructor: "Justice Verma",
    // instructorBio:
    //   "Retired High Court Judge with 30 years of judicial experience and expertise in constitutional law.",
    // instructorAvatar: "https://randomuser.me/api/portraits/men/82.jpg",
    color: "#EF4444",
    students: 48,
    level: "Expert",
    description:
      "This specialized training prepares legal professionals for judicial positions and enhances judicial knowledge. Participants learn judicial ethics, courtroom management, and judgment writing skills. The program includes mock trials and simulations for practical experience. Graduates receive certification from the National Judicial Academy recognized across legal institutions.",
      descriptions:"This unique course is a blend of legal education and personality development tailored for aspiring judicial officers, lawyers, and legal professionals. It covers core legal subjects including civil, criminal, and constitutional law, courtroom procedures, judgment writing, and legal drafting. The program also includes public speaking, stress management through yoga and meditation, time management, and ethics in legal practice. Participants gain insights from judges, legal scholars, and industry experts, and engage in moot courts and case simulations. It prepares candidates for judicial exams and careers in the judiciary with a focus on holistic competency.",
    syllabus: [
      "Judicial Ethics & Conduct",
      "Courtroom Management",
      "Judgment Writing Skills",
      "Alternative Dispute Resolution",
      "Contemporary Legal Issues",
      "Mock Trials & Simulations",
    ],
    certification:
      "Certificate of Judicial Training from National Judicial Academy",
    prerequisites: "Law degree and minimum 5 years legal practice",
    learningOutcomes: [
      "Enhanced understanding of judicial processes",
      "Improved decision-making skills",
      "Professional judgment writing ability",
      "Knowledge of judicial reforms",
    ],
    // startDates: ["2024-02-01", "2024-07-01"],
    // price: "₹75,000",
    // discountPrice: "₹65,000 (for government employees)",
  },
  {   
    id:6,
    title: "Advanced Meditation Techniques",
    duration: "4 Months",
    image:
      "/img/medi.jpg",
    rating: 4.6,
    reviews: 92,
    category: "Wellness",
    // instructor: "Ananya Desai",
    // instructorBio:
    //   "Meditation teacher trained in Tibetan and Vipassana traditions with 10 years of teaching experience.",
    // instructorAvatar: "https://randomuser.me/api/portraits/women/63.jpg",
    color: "#8B5CF6",
    students: 76,
    level: "Intermediate",
    description:
      "This course offers a deep exploration of meditation traditions with practical applications. Students learn mindfulness-based stress reduction, loving-kindness meditation, and body scan techniques. The program includes training in walking meditation and retreat planning. Graduates receive certification to teach meditation with skills adaptable to diverse needs and populations.", 
      descriptions:"An elite-level program for serious practitioners and instructors wishing to go deeper into meditative sciences. This course explores powerful meditation forms such as Raja Yoga, Japa (mantra repetition), Silent Meditation (Mauna), Antar Mouna (inner silence), Trataka (gazing), and energy channeling via breath and awareness. Participants study yogic texts, practice prolonged silent sittings, and attend guided inner transformation sessions. Emphasis is placed on the psychological, neurological, and spiritual dimensions of meditation. The training fosters deep inner peace, emotional healing, and expanded states of consciousness. Suitable for wellness coaches, advanced yoga instructors, and spiritual aspirants.",
    syllabus: [
      "Mindfulness-Based Stress Reduction",
      "Loving-Kindness Meditation",
      "Body Scan Techniques",
      "Walking Meditation",
      "Retreat Planning",
      "Teaching Methodology",
    ],
    certification: "Certificate in Meditation Instruction",
    prerequisites: "Regular meditation practice for at least 6 months",
    learningOutcomes: [
      "Deepened personal meditation practice",
      "Ability to guide various meditation techniques",
      "Understanding of different meditation traditions",
      "Skills to adapt practices for different needs",
    ],
    // startDates: ["2023-12-01", "2024-04-15"],
    // price: "₹28,000",
    // discountPrice: "₹24,000 (for group enrollment)",
  },
];